### ISSUE TITLE
Upcoming ETN fork?

### ISSUE THREAD

**Issue by Velkas** [ParthK117/ezminer#1]
Is there any word on the update for the fork coming up?

**Comment by ParthK117** [comment]
Sorry, I wasn't aware that people still used this miner since AIOminer has since surpassed it. I'll update it soon!

**Comment by ParthK117** [comment]
namecheap has updated their TLS so it's incompatible with ezminer 1.1.0, but electroneum has rolled back to asic friendly cryptonight, so if you just click through all the errors and use a custom pool the miner should work again as is. But since asics have taken over i don't know if you should keep mining electroneum. 2.0.0 will be coming out soon regardless.
